version: '3'

services:

  backend:
    build: ./Backend/src
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/gymrats
      - REDIS_URI=redis://redis:6379

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"
